server:
  port: 8080

spring:
  application:
    name: expos-system-app
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: local

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://localhost:8848?namespace=

