server:
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useSSL=false&verifyServerCertificate=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379

dubbo:
  registry:
    address: nacos://localhost:8848?namespace=expos-system

knife4j:
  enable: true

