server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://182.61.149.225:3306/fate_flow?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: fate
    password: fate_dev
    driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
