spring:
  profiles:
    active: dev
dubbo:
  application:
    name: consumerApplication
  consumer:
    retries: 0
    timeout: 5000
  scan:
    base-packages: com.fjh.dubbo
  registry:
    address: nacos://localhost:8848?namespace=