spring:
  profiles:
    active: dev
dubbo:
  application:
    name: consumerApplication
  provider:
    group: test
  consumer:
    group: test
    retries: 0
    timeout: 5000
  scan:
    base-packages: com.fjh.dubbo
  registry:
    address: nacos://localhost:8848?namespace=aec23b43-4599-4fdd-b8a2-ec28d937769f