spring:
  application:
    name: email-app
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    port: 25
    username: 8
    password: s


swagger:
  title: 邮件api
  desc: 邮件api文档
  version: 1.0.0
  group: 邮件组
  enable: true
