server:
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&verifyServerCertificate=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root21.
  redis:
    host: localhost
    port: 6379


knife4j:
  enable: true

