spring:
  profiles:
    active: dev
  application:
    name: providerApplication
dubbo:
  application:
    name: providerApplication
  provider:
    group: expos-middle-admin
    port: 20888
  consumer:
    group: expos-middle-admin
    retries: 0
    timeout: 5000
  scan:
    base-packages: com.fjh.dubbo
  registry:
    address: nacos://localhost:8848?namespace=aec23b43-4599-4fdd-b8a2-ec28d937769f