spring:
  profiles:
    active: dev
  application:
    name: providerApplication
dubbo:
  application:
    name: providerApplication
  scan:
    base-packages: com.fjh.dubbo
  registry:
    address: nacos://182.61.149.225:8848?namespace=