server:
  port: 8085
dubbo:
  application:
    name: providerApplication
  provider:
    port: 20880
  consumer:
    retries: 0
    timeout: 5000
  scan:
    base-packages: com.fjh.dubbo
  registry:
    address: nacos://localhost:8848?namespace=